=== Stanford-EAO/OPGEEv4/opgee/etc/attributes.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' elementFormDefault='qualified'>
    <xs:element name='AttrDefs'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='ClassAttrs' maxOccurs='unbounded'/>
            </xs:sequence>
        </xs:complexType>
	  </xs:element>

    <xs:element name='ClassAttrs'>
        <xs:complexType>
            <xs:choice maxOccurs='unbounded'>
                <xs:element minOccurs='0' ref='Options'/>
                <xs:element minOccurs='0' ref='AttrDef'/>
            </xs:choice>
            <xs:attribute name='name' use='required' type='xs:NCName'/>
        </xs:complexType>
    </xs:element>

    <xs:element name='Options'>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='Option'/>
            </xs:sequence>
            <xs:attribute name='name' use='required' type='xs:string'/>
            <xs:attribute name='default' use='required' type='xs:string'/>
        </xs:complexType>
    </xs:element>

    <xs:element name='Option'>
        <xs:complexType mixed='true'>
            <xs:attribute name='desc' type='xs:string'/>
            <xs:attribute name='label' type='xs:string'/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Requires"/>   <!-- defines dependencies for SmartDefaults -->

    <xs:element name='AttrDef'>
        <xs:complexType mixed='true'>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="Requires"/>
            </xs:sequence>
            <xs:attribute name='desc'/>
            <xs:attribute name='name' use='required' type='xs:string'/>
            <xs:attribute name='options' type='xs:string'/>
            <xs:attribute name='type' type='xs:NCName'/>
            <xs:attribute name='unit'/>
            <xs:attribute name='exclusive'/>      <!-- exclusive attributes -->
            <xs:attribute name='synchronized'/>   <!-- synchronized attributes -->
            <xs:attribute name='has_smart_default' type='xs:boolean'/>

            <!-- Numeric constraints -->
            <xs:attribute name="GT" type="xs:decimal"/>
            <xs:attribute name="GE" type="xs:decimal"/>
            <xs:attribute name="LT" type="xs:decimal"/>
            <xs:attribute name="LE" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Stanford-EAO/OPGEEv4/opgee/etc/attributes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file defines attributes of standard OPGEE classes / XML elements, including
     name, short description, unit (if any) and deterministic default values. It is used
     to support parsing the XML model definition and to used by the Smart Default system
     to fill in unspecified attributes. It can also eventually support a GUI, e.g., in
     creating pulldown menus of options for categorical parameters and radio buttons for
     binaryÂ ones.
     -->
<AttrDefs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="attributes.xsd">
  <ClassAttrs name="Model">
    <!-- Maximum number of iterations for process loops -->
    <AttrDef name="maximum_iterations" type="int">10</AttrDef>

    <!-- Change threshold for iteration loops. Requires a Process to set a change variable. -->
    <AttrDef name="maximum_change" type="float">0.001</AttrDef>
  </ClassAttrs>

  <ClassAttrs name="Stream">
    <!-- the zero values aren't real defaults; they just avoid having None as a default -->
    <AttrDef name="temperature" type="float" unit="degF">0</AttrDef>
    <AttrDef name="pressure" type="float" unit="psia">0</AttrDef>
  </ClassAttrs>

  <ClassAttrs name="Analysis">
    <Options name="GWP horizon" default="100">
      <Option label="20 year">20</Option>
      <Option label="100 year">100</Option>
    </Options>
    <Options name="GWP version" default="AR5">
      <Option>AR4</Option>
      <Option>AR5</Option>
      <Option label="AR5 with C-cycle feedback">AR5_CCF</Option>
    </Options>
    <Options name="Functional unit" default="oil">
      <Option label="1 MJ Crude oil">oil</Option>
      <Option label="1 MJ Natural gas">gas</Option>
    </Options>
    <Options name="Energy basis" default="LHV">
      <Option label="Lower heating value">LHV</Option>
      <Option label="Higher heating value">HHV</Option>
    </Options>

    <AttrDef name="GWP_horizon" options="GWP horizon" type="int" unit="years"/>
    <AttrDef name="GWP_version" options="GWP version" type="str"/>
    <AttrDef name="functional_unit" options="Functional unit" type="str"/>
    <AttrDef name="energy_basis" options="Energy basis" type="str"/>
  </ClassAttrs>

  <!-- Attributes shared by all Processes. These values can be overridden in subprocesses -->
  <ClassAttrs name="Process">
    <AttrDef name="leak_rate" type="float" desc="Fraction of gas streams leaked to environment" unit="fraction">0.002</AttrDef>
  </ClassAttrs>

  <ClassAttrs name="Field">
    <!-- Production methods -->
    <AttrDef name="downhole_pump" type="binary" desc="Downhole pump">1</AttrDef>
    <AttrDef name="water_reinjection" type="binary" desc="Water reinjection">1</AttrDef>
    <AttrDef name="natural_gas_reinjection" type="binary" desc="Natural gas reinjection">1</AttrDef>
    <AttrDef name="water_flooding" type="binary" desc="Water flooding">0</AttrDef>
    <AttrDef name="gas_lifting" type="binary" desc="Gas lifting">0</AttrDef>

    <!-- mutually exclusive -->
    <AttrDef name="gas_flooding" type="binary" desc="Gas flooding" exclusive="flooding">0</AttrDef>
    <AttrDef name="steam_flooding" type="binary" desc="Steam flooding" exclusive="flooding">0</AttrDef>

    <Options name="oil_sands_mine_type" default="None">
      <Option>None</Option>
      <Option>Integrated with upgrader</Option>
      <Option>Non-integrated with upgrader</Option>
    </Options>
    <AttrDef name="oil_sands_mine" options="oil_sands_mine_type" desc="Oil sands mine"/>


    <!-- synchronized - these are just for testing purposes -->
    <AttrDef name="sync_attr_1" type="binary" synchronized="sync_test">0</AttrDef>
    <AttrDef name="sync_attr_2" type="binary" synchronized="sync_test">0</AttrDef>

    <!-- Field properties -->
    <AttrDef name="country" desc="Field location (country)" type="str">Generic</AttrDef>
    <AttrDef name="name" desc="Field name" type="str">Generic</AttrDef>
    <AttrDef name="age" unit="yr" desc="Field age" type="float" GT="0" LT="150">38</AttrDef>
    <AttrDef name="depth" unit="ft" desc="Field depth" type="float" GT="0" LT="25000">7240.0</AttrDef>
    <AttrDef name="oil_prod" unit="bbl_oil/d" desc="Oil production volume" type="float" GT="0">2098.0</AttrDef>
    <AttrDef name="num_prod_wells" desc="Number of producing wells" type="int" GT="0">24</AttrDef>
    <AttrDef name="num_water_inj_wells" desc="Number of water injecting wells" type="int" GE="0">20</AttrDef>
    <AttrDef name="well_diam" unit="in" desc="Well diameter" type="float" GT="0">2.78</AttrDef>
    <AttrDef name="prod_index" unit="bbl_oil/(psia*day)" type="float" desc="Productivity index">17.0</AttrDef>
    <AttrDef name="res_press" unit="psia" desc="Average reservoir pressure" type="float">1556.6</AttrDef>
    <AttrDef name="res_temp" unit="degF" desc="Average reservoir temperature" type="float">200.0</AttrDef>
    <AttrDef name="res_thickness" unit="ft" desc="Average reservoir thickness" type="float">50</AttrDef>
    <AttrDef name="res_perm" unit="mD" desc="Reservoir permeability" type="float">100</AttrDef>
    <AttrDef name="wellhead_pressure" type="float" unit="psia" >500</AttrDef>
    <AttrDef name="wellhead_temperature" type="float" unit="degF" >80</AttrDef>
    <AttrDef name="offshore" type="binary" desc="Offshore?">0</AttrDef>
    <!-- Fluid properties -->
    <AttrDef name="API" desc="API gravity of produced crude" unit="degAPI" type="float" has_smart_default="true">
      <Requires>GOR</Requires>
    </AttrDef>
    <AttrDef name="API_bitumen" unit="degAPI" type="float" desc="API gravity of bitumen">8.0</AttrDef>
    <AttrDef name="total_dissolved_solids" desc="water total dissolved solid (TDS)" unit="mg/L" type="float">5000.0</AttrDef>
    <AttrDef name="gas_comp_N2" unit="mol_pct" type="float">2.86</AttrDef>
    <AttrDef name="gas_comp_CO2" unit="mol_pct" type="float">0.33</AttrDef>
    <AttrDef name="gas_comp_C1" unit="mol_pct" type="float">89.18</AttrDef>
    <AttrDef name="gas_comp_C2" unit="mol_pct" type="float">5.30</AttrDef>
    <AttrDef name="gas_comp_C3" unit="mol_pct" type="float">1.62</AttrDef>
    <AttrDef name="gas_comp_C4" unit="mol_pct" type="float">0.71</AttrDef>
    <AttrDef name="gas_comp_H2S" unit="mol_pct" type="float">0.0</AttrDef>    <!-- TODO: needs a default value -->
    <!-- Production practices -->
    <Options name="Flood gases" default="NG">
      <Option desc="Natural gas">NG</Option>
      <Option desc="Nitrogen">N2</Option>
      <Option desc="Carbon dioxide">CO2</Option>
    </Options>
    <Options name="Liquids unloading" default="None">
      <Option>Plunger</Option>
      <Option>No plunger</Option>
      <Option>None</Option>
    </Options>
    <Options name="source_CO2" default="reservoir">
      <Option desc="natural subsurface reservoir">Reservoir</Option>
      <Option>Anthropogenic</Option>
    </Options>
    <AttrDef name="GOR" desc="Gas-to-oil ratio" unit="scf/bbl_oil" type="float">2429.3</AttrDef>

    <AttrDef name="WOR" desc="Water-to-oil ratio" unit="bbl_water/bbl_oil" type="float">6.0</AttrDef>
    <AttrDef name="WOR-MEAN" desc="WOR mean (deps. on age)" unit="" type="float">6.0</AttrDef>
    <AttrDef name="WOR-SD" desc="WOR std deviation (deps. on age)" unit="" type="float">1.4</AttrDef>

    <AttrDef name="WIR" desc="Water injection ratio" unit="bbl_water/bbl" type="float">7.0</AttrDef>
    <AttrDef name="GLIR" desc="Gas lifting injection ratio" unit="scf/bbl_liquid" type="float">364.0</AttrDef>
    <AttrDef name="GFIR" desc="Gas flooding injection ratio" unit="scf/bbl_oil" type="float">3644.0</AttrDef>
    <AttrDef name="flood_gas_type" desc="Flood gas" options="Flood gases" type="str"/>
    <AttrDef name="liquids_unloading" options="Liquids unloading" type="str"/>
    <AttrDef name="perc_CO2_breakthrough" desc="Fraction of CO2 breaking through to producers" unit="percent" type="float">59</AttrDef>
    <AttrDef name="source_CO2" desc="" options="source_CO2" type="str"/>
    <AttrDef name="perc_sequestration_credit" desc="Percentage of sequestration credit assigned to the oilfield" unit="percent" type="float">0</AttrDef>
    <AttrDef name="SOR" desc="Steam-to-oil ratio" unit="bbl_steam/bbl_oil" type="float">0</AttrDef>
    <AttrDef name="fraction_elec_onsite" desc="Fraction of required electricity generated onsite" type="float">0.0</AttrDef>
    <AttrDef name="fraction_remaining_gas_inj" desc="Fraction of remaining gas reinjected" type="float">0.5</AttrDef>
    <AttrDef name="fraction_water_reinjected" desc="Fraction of water produced that is reinjected" type="float">1.0</AttrDef>
    <AttrDef name="fraction_steam_cogen" desc="Fraction of steam generation via co-generation" type="float">0.0</AttrDef>
    <AttrDef name="fraction_steam_solar" desc="Fraction of steam generation via solar thermal" type="float">0.0</AttrDef>
    <AttrDef name="pressure_outlet" type="float" unit="psia" desc="Separator pressure (final if multi-stage)">100.0</AttrDef>
    <AttrDef name="temperature_outlet" type="float" unit="degF" desc="Separator temperature (final if multi-stage)">90.0</AttrDef>
    <AttrDef name="gas_pressure_after_boosting" type="float" unit="psia" desc="Separator gas outlet pressure after boosting compressors">500</AttrDef>
    <AttrDef name="eta_compressor" type="float" unit="percent" desc="Compressor efficiency">75.0</AttrDef>
    <!-- Processing practices -->
    <Options name="upgrader_type" default="None">
      <Option>None</Option>
      <Option>Delayed coking</Option>
      <Option>Hydroconversion</Option>
      <Option desc="Combined hydroconversion and fluid coking">Combined</Option>
    </Options>
    <Options name="crude_oil_dewatering_output" default="CrudeOilStabilization">
      <Option desc="Heavy oil upgrading">HeavyOilUpgrading</Option>
      <Option desc="Heavy oil dilution">HeavyOilDilution</Option>
      <Option desc="Crude oil stabilization">CrudeOilStabilization</Option>
    </Options>
    <Options name="gas_processing_path" default="Acid wet gas">
